### ISSUE TITLE
It is open source?

### ISSUE THREAD

**Issue by ignaloidas** [GPUOpen-LibrariesAndSDKs/RadeonRays_SDK#206]
The [page](https://gpuopen.com/radeon-rays/) says that this is not open source, yet LICENSE.txt is MIT license. Please clear up on licensing.

**Comment by SicLuceatLux** [comment]
Does this mean one can request the sourcecode even with legal background ;) ?

**Comment by shmerl** [comment]
Why is it no longer open source?

**Comment by himanshugoel2797** [comment]
Presumably MIT is meant to apply to the headers + samples?

**Comment by yozhijk** [comment]
Hi guys,
Thanks for still being with us and for the feedback you have provided so far. It has been decided yesterday to open-source most of RadeonRays4 and put AMD specific IP in closed-source modules (source will be available upon request under SLA).

-Dmitry

**Comment by melMass** [comment]
@yozhijk I was about to open an issue but I think it applies here, is there a reason for the macOs10.15+ requirement? I wanted to build from source when I realized there was none. I'm using 10.14 for various reasons for now :/ 

Thanks

**Comment by SicLuceatLux** [comment]
Thx @yozhijk great move !

**Comment by lightistor** [comment]
@yozhijk I presume you meant NDA as opposed to SLA.

**Comment by qhaas** [comment]
Question is, [how long will legal limbo last](https://github.com/GPUOpen-LibrariesAndSDKs/RadeonRays_SDK/issues/212#issuecomment-656760306):  `We're working on open sourcing what we can from the latest version with legal.`

**Comment by itmanager85** [comment]
> Hi guys,
>It has been decided yesterday to open-source most of RadeonRays4
> -Dmitry

So when will we see the source code of RadeonRays4 ? it's been almost a year since you promised to provide it ..

**Comment by bsavery** [comment]
> So when will we see the source code of RadeonRays4 ? it's been almost a year since you promised to provide it ..

I would argue about 7.5 months being "almost a year" ;) However, that being said, please be patient.  The people replying here are developers, not the legal dept.  We'll post an update when we can!

**Comment by Hi-Angel** [comment]
> > So when will we see the source code of RadeonRays4 ? it's been almost a year since you promised to provide it ..
> 
> I would argue about 7.5 months being "almost a year" ;) However, that being said, please be patient. The people replying here are developers, not the legal dept. We'll post an update when we can!

Well, speaking of developers: if this project is even maintained, there's clearly something that could be done without waiting for legal team. Specifically, pull requests been piling up since 2018 year. Someone could review and accept them. That said, right now all PRs would clearly be in conflict because of the situation discussed. That could be worked around by first accepting https://github.com/GPUOpen-LibrariesAndSDKs/RadeonRays_SDK/pull/210 which reverts commits that brought those binaries, and then review and accept the rest of PRs.

**Comment by Hi-Angel** [comment]
Btw, there is something to be said about the AMD development team. I leave this comment specifically for AMD devs, because you folks will need to have an internal talk on your team.

Let's go back in time to July 2018. That was the time last commit was made to the repo. Then, some developer, let's call him Bob, decided to make another change to RadeonRays SDK. He finds some old private repo from before 2016 *(in 2016 development moved to github)*, and makes a commit there. Why nobody noticed that? Do you even have a codereview? If he was explicitly asked to commit to the internal repo, why no one questioned that, didn't contact the legal team? And Bob wasn't the last dev who did that, there was a slew of others, and no one asked "why do we not use the Github repo, the development is been done there since 2016 year".

Please folks, bring this up on the next internal meeting, because this looks pretty frustrating, what a team…

**Comment by gbeatty** [comment]
It must be a shit show over there in AMD dev land. Product after product goes through this same cycle of release promising product to open source -> bugs & PR pile up which all  get ignored -> product dies because there's no support.  Why can't they get their act together?

**Comment by ignaloidas** [comment]
Closing since the source got published under an open source license.
