### ISSUE TITLE
bvh.sah.usesplits and some other options not implemented?

### ISSUE THREAD

**Issue by dylanlacewell** [GPUOpen-LibrariesAndSDKs/RadeonRays_SDK#58]
This option is documented in firerays.h:

`
// option "bvh.sah.usesplits" values {0(default),1} (allow spatial splits for BVH)`

But it seems to have no effect on benchmarks, and I can't find any uses of it with GetOptions in the source tree. 

Same for "trisah", "overlaparea" and other options for bvh.sah.*

It would also be nice to have a way to print all available options as a query, or list the options that have been set.  I like being able to set options as strings, but it's easy to misspell something and have it be silently ignored.

**Comment by dylanlacewell** [comment]
bump.  Is this a known issue, or is there a way to enable spatial splits that I'm missing?  

For a perf measurement, I'd like to try options that give me (a) the fastest build times, and (b) the best expected traversal performance in general.

**Comment by yozhijk** [comment]
Hi @dylanlacewell ,

You are right, I have removed spatial splits while doing open-sourcing since we are going to need some additional legal checks on that.  So currently the following options are supported:

acc.type:
- bvh - binary bvh with stackless traversal (fastest one for shadow rays on AMD Hawaii, Fiji)
- fatbvh - binary bvh with 2 bboxes per node, stacked traversal with LDS caching (fastest one in general on AMD)
- hlbvh - morton-code based GPU build (fastest to build, but slow to traverse)
 
bvh.builder (only apply to bvh, fatbvh):
 - simple - use median split
 - sah - use surface area heuristic

bvh.force2level (only apply to bvh):
true - force using 2 level hierarchy even there is no instances or motion blur (faster refit in case of object transforms
false - only use 2 level if instances or motion blur show up in the scene

bvh.forceflat:
true - duplicate geometry for instances and use single level BVH in any case
false - use 2 level bvh for instances

As for you question about splits: I hope I can enable it after Siggraph (it certainly gives some speed up for Sponza-like scenes).

**Comment by dylanlacewell** [comment]
Thanks for confirming this, @yozhijk.  That's what I figured, just wanted to be fair when collecting numbers.  I was in fact testing the Sponza scene when I noticed the flag didn't work :)

**Comment by yozhijk** [comment]
Hi @dylanlacewell ,

I have implemented SBVH here: https://github.com/GPUOpen-LibrariesAndSDKs/RadeonRays_SDK/commit/9cd15faf90ecbf8694cd7d1cd7951a42b8e33b94

It is not yet complete (no un-splitting part from the original paper) and I did not have time to very it is fully correct, but you can play with it if you want. 

Note, that parameter names have changed a little bit, refer to header file to get correct ones. 

We will continue working on it, addind performance tests and the stuff.

**Comment by yozhijk** [comment]
Closing as sbvh is fully implemented
