### ISSUE TITLE
Concurrent calling of QueryIntersection and/or QueryOcclusion

### ISSUE THREAD

**Issue by p32blo** [GPUOpen-LibrariesAndSDKs/RadeonRays_SDK#96]
After taking code from a project using _Embree_ with **multiple threads** and trying to use _RadeonRays_, there an issue with calling `QueryIntersection` or `QueryOcclusion` from different threads. The output of this queries can end with invalid results. For example some times `shapeid` returns a large negative value (ex: -401765336), which should not happen as far as I can understand, leading to segfaults subsequently.

Is it the case that this calls should not be done in parallel? If this is, how should RadeonRays be handled when multithreading?

Thank you in advance

edit: [[rays-test.tar.gz](https://github.com/GPUOpen-LibrariesAndSDKs/RadeonRays_SDK/files/546742/rays-test.tar.gz)] Attached a minimal project that displays the problem. Note that by using `#pragma omp critical` with the queries (commented in the code) the results become correct.

**Comment by yozhijk** [comment]
Yes, this is expected result actually since RadeonRays is using single GPU submission queue and it is up to the user to synchronise an access to this queue. However if you create two RadeonRays api instances you can pretty much use them concurrently leaving synchronisation for the driver. In this case you are going to need a bit more buffer management.

**Comment by yozhijk** [comment]
Note, that synchronising calls should not cause too much of an overhead since calls are non-blocking  and typically not taking long to finish.

**Comment by yozhijk** [comment]
Closing as obsolete
